services:
    exs_tracking.cambuilder_manager:
        class: 'EXS\LanderTrackingCambuilderBundle\Service\TrackingParameterManager\CambuilderTrackingParameterManager'
        arguments:
            - '%exs_lander_tracking_cambuilder.default_cmp%'
        tags:
            - { name: 'exs_tracking.parameter_extracter', priority: 100 }
            - { name: 'exs_tracking.parameter_formatter' }
