services:
    exs_tracking.cambuilder_manager:
        class: 'EXS\LanderTrackingCambuilderBundle\Service\TrackingParameterManager\CambuilderTrackingParameterManager'
        tags:
            - { name: 'exs_tracking.parameter_extracter' }
            - { name: 'exs_tracking.parameter_formatter' }
